### PR TITLE
Add option to create directory missing in dest dir

### PR DESCRIPTION
**Pull request by TheGuit**

### CODE REVIEW

**Comment by TheGuit** [comment]
@staempfli-webteam @jalogut Is the anyone who could watch at this PR ?

Regards,

**Comment by jalogut** [comment]
Hi @TheGuit 

Sorry for the delay. I just merged it and create a new version `1.1`

**Comment by jalogut** [comment]
Hi again @TheGuit 

I forgot to say thank you very much for your contribution 😃

**Comment by TheGuit** [comment]
Hello @jalogut thanks for all :)

**Pull request merged**
